Initial pull request
metglobal-compass/spring-changelog-viewer pull request #1
Opened 2020-05-06 13:16 UTC by EmreKp

Mikroservislerimizde changelog görüntülemek için kullanılacak bir yardımcı paket, HTML rendering vs. şu an için basic hazırlandı, ileriki aşamalarda optimize edilebilir.

2020-05-06 13:42 UTC, MehGokalp commented on pom.xml
> +  <version>1.0.0</version>
Versiyon scriptinden dolayı 0.1.0 olarak düzeltmemiz gerekebilir burayı

2020-05-06 13:59 UTC, EmreKp commented on pom.xml
> +  <version>1.0.0</version>
bunu iyi dedin, bizim servis versiyonlarıyla da uyumlu olur hem.

2020-05-06 14:01 UTC, MehGokalp commented on README.md
> +Changelog renderer written in Spring boot
Buraya repository hakkında açıklayıcı bir metin hazırlayıp eklemeliyiz

2020-05-06 14:02 UTC, EmreKp commented on README.md
> +Changelog renderer written in Spring boot
aynen en sona bırakmıştım burayı, arada kaynamış :)

2020-05-06 14:03 UTC, MehGokalp requested changes
Travis CI entegrasyonu ve ekstra olarak code coverage entegrasyonu yapılabilir.

2020-05-06 14:08 UTC, MehGokalp commented on TEST.md
> +- This is 2nd list item.
bunları main directory den farklı bir yere alsak daha güzel olur gibime geldi

2020-05-06 14:08 UTC, MehGokalp commented on test.html
> +<h2>Test Changelog</h2>
bu dosyayı da TEST.md gibi, dizinini değiştirsek hoş olur gibi

2020-05-06 14:36 UTC, EmreKp commented on README.md
> +Changelog renderer written in Spring boot
metni ekledim umarım anlaşılır olmuştur.

2020-05-06 14:39 UTC, EmreKp commented on TEST.md
> +- This is 2nd list item.
changelog'un yer aldığı kısımla aynı olsun diye bu şekilde yaptım, normalde statik dosyalara resources klasöründen erişiliyor, amaç bu dosyaya changelog gibi erişebilmek, ismini changelog olarak da yapmayı düşündüm, ama farklı dosyaya ne tepki verecek onu test etmek istedim. bunun adını da değiştirebilrim, veya resources dışında sub dizin açıp oraya da koyabilirim.

2020-05-06 14:40 UTC, EmreKp commented on test.html
> +<h2>Test Changelog</h2>
ilgili yorum: https://github.com/metglobal-compass/spring-changelog-viewer/pull/1#discussion_r420844368

2020-05-06 14:52 UTC, EmreKp commented
@MehGokalp 

> Travis CI entegrasyonu ve ekstra olarak code coverage entegrasyonu yapılabilir.

Bunlar sanırım testleri push sonrası koşmaya yarayacak, ayrıca paketler için yeni Packages entegrasyonu da yapmayı düşündüm ancak paketi import etmek dosya sistemi bazında da authentication gerektirdiği için şimdilik yine JitPack üzerinden yürümeye karar verdim, authsuz import gelene kadar en kolay çözüm şu anlık bu.

2020-05-06 15:11 UTC, EmreKp commented
deploy kullanmadığımız için sadece build ve testler için hazırlanmış halihazırda Github workflow'u mevcut, ancak Travis'in artılarını tam olarak bilmiyorum, repoya paket ekleme hizmeti yok sanırım.

2020-05-08 07:49 UTC, goksagun commented on src/main/java/com/compass/changelog/util/FileConverter.java
> +      throw new RuntimeException("There was an error reading file");
Exception özelleştirmemiz lazım, özellikle bu tür third-party paketlerde çok önemlihata ayıklamak açısından, örneğin;
```java
// ../path-to-package/exception/FileReadException.java

public class FileReadException extends RuntimeException {


}
```

2020-05-11 09:42 UTC, EmreKp commented on TEST.md
> +- This is 2nd list item.
dosyalar test_files altında ayrı bir klasöre ayrıldı.

2020-05-11 14:33 UTC, EmreKp commented
Coverage raporu oluşturma ve CodeCov'a yükleme için step eklendi, raporlara https://codecov.io/gh/metglobal-compass adresinden ulaşılabilir.

2020-05-12 12:36 UTC, MehGokalp approved these changes

2020-05-13 06:37 UTC, goksagun approved these changes

2020-05-13 06:37 UTC, merged